apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app-container
          image: docker.apple.com/sonal_karn/flask_app:2.2
          ports:
            - containerPort: 8080
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: sqlite:///app/sqlite/User.sqlite3  # Mount path in the container
          volumeMounts:
            - name: sqlite-volume
              mountPath: /app/sqlite  # Mount path in the container
      volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: sqlite-pvc
